version: "3.7"

services:

    reverse-proxy:
        image: "jwilder/nginx-proxy"
        container_name: "reverse-proxy"
        volumes:
            - " ./shared/nginx/vhost.d:/etc/nginx/vhost.d"
            - "./shared/nginx/certs:/etc/nginx/certs:ro"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        restart: "always"
        networks:
            proxy: null
            identityserverui:
                aliases:
                - sts.je-idp.jeanedwards.com
                - admin.je-idp.jeanedwards.com
                - admin-api.je-idp.jeanedwards.com
                - icce.jeanedwards.com
                - icce-api.jeanedwards.com
        ports:
            - "80:80"
            - "443:443"

networks:
  proxy:
    driver: bridge
  je-jwilder-nginx:
    driver: bridge